// Code generated by protoc-gen-go. DO NOT EDIT.
// source: testing/fake/proto/fake.proto

package gnmi_fake

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	gnmi "github.com/openconfig/gnmi/proto/gnmi"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type State int32

const (
	State_STOPPED State = 0
	State_INIT    State = 1
	State_RUNNING State = 2
)

var State_name = map[int32]string{
	0: "STOPPED",
	1: "INIT",
	2: "RUNNING",
}

var State_value = map[string]int32{
	"STOPPED": 0,
	"INIT":    1,
	"RUNNING": 2,
}

func (x State) String() string {
	return proto.EnumName(State_name, int32(x))
}

func (State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0c8aeeab0e585ec7, []int{0}
}

type Config_ClientType int32

const (
	Config_GRPC           Config_ClientType = 0
	Config_STUBBY         Config_ClientType = 1
	Config_GRPC_GNMI      Config_ClientType = 2
	Config_GRPC_GNMI_PROD Config_ClientType = 3
)

var Config_ClientType_name = map[int32]string{
	0: "GRPC",
	1: "STUBBY",
	2: "GRPC_GNMI",
	3: "GRPC_GNMI_PROD",
}

var Config_ClientType_value = map[string]int32{
	"GRPC":           0,
	"STUBBY":         1,
	"GRPC_GNMI":      2,
	"GRPC_GNMI_PROD": 3,
}

func (x Config_ClientType) String() string {
	return proto.EnumName(Config_ClientType_name, int32(x))
}

func (Config_ClientType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0c8aeeab0e585ec7, []int{2, 0}
}

// Configuration is used to store all agent configuration for the fake agent
// server.  Each config describes a single agent hosted on the server.
type Configuration struct {
	// Repeated list of targets to emulate.
	Config               []*Config `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Configuration) Reset()         { *m = Configuration{} }
func (m *Configuration) String() string { return proto.CompactTextString(m) }
func (*Configuration) ProtoMessage()    {}
func (*Configuration) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c8aeeab0e585ec7, []int{0}
}

func (m *Configuration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Configuration.Unmarshal(m, b)
}
func (m *Configuration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Configuration.Marshal(b, m, deterministic)
}
func (m *Configuration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Configuration.Merge(m, src)
}
func (m *Configuration) XXX_Size() int {
	return xxx_messageInfo_Configuration.Size(m)
}
func (m *Configuration) XXX_DiscardUnknown() {
	xxx_messageInfo_Configuration.DiscardUnknown(m)
}

var xxx_messageInfo_Configuration proto.InternalMessageInfo

func (m *Configuration) GetConfig() []*Config {
	if m != nil {
		return m.Config
	}
	return nil
}

type Credentials struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Credentials) Reset()         { *m = Credentials{} }
func (m *Credentials) String() string { return proto.CompactTextString(m) }
func (*Credentials) ProtoMessage()    {}
func (*Credentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c8aeeab0e585ec7, []int{1}
}

func (m *Credentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Credentials.Unmarshal(m, b)
}
func (m *Credentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Credentials.Marshal(b, m, deterministic)
}
func (m *Credentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credentials.Merge(m, src)
}
func (m *Credentials) XXX_Size() int {
	return xxx_messageInfo_Credentials.Size(m)
}
func (m *Credentials) XXX_DiscardUnknown() {
	xxx_messageInfo_Credentials.DiscardUnknown(m)
}

var xxx_messageInfo_Credentials proto.InternalMessageInfo

func (m *Credentials) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Credentials) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// Config is a collection of values that together represent the update streams
// for one or more fake devices.
type Config struct {
	// The target for which the fake will publish values for.
	Target string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	// Port for the agent to listen on. If 0 or unset the agent will pick a port
	// for this agent.
	Port int32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	// A global random seed used in generating subsequent values. Set to have
	// reproducible results.
	Seed int64 `protobuf:"varint,6,opt,name=seed,proto3" json:"seed,omitempty"` // Deprecated: Do not use.
	// The list of values generated.  Each value will contain its corresponding
	// target as the first string in the event.GetValue().path meaning that it is
	// possible to generate streams that will be rejected by the cache for testing
	// purposes.
	Values []*Value `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"` // Deprecated: Do not use.
	// Setting disable sync will keep the configured client from autogenerating a
	// sync message. This allows negative testing on sync handling.
	DisableSync bool `protobuf:"varint,4,opt,name=disable_sync,json=disableSync,proto3" json:"disable_sync,omitempty"`
	// Type of client to fake either Stubby or GRPC based fake.
	ClientType Config_ClientType `protobuf:"varint,5,opt,name=client_type,json=clientType,proto3,enum=gnmi.fake.Config_ClientType" json:"client_type,omitempty"`
	// Disable EOF will hold open the subscription and not automagically close
	// the stream once the value queue is empty.
	DisableEof bool `protobuf:"varint,7,opt,name=disable_eof,json=disableEof,proto3" json:"disable_eof,omitempty"`
	// Per RPC credentials for the agent. If not set no per RPC auth will be used.
	Credentials *Credentials `protobuf:"bytes,8,opt,name=credentials,proto3" json:"credentials,omitempty"`
	// TLS cert for use on the agent. If not set the transport will not be TLS.
	Cert []byte `protobuf:"bytes,9,opt,name=cert,proto3" json:"cert,omitempty"`
	// Honor the delay between events in the generated value streams. Default will
	// play events as fast as the can be streamed.
	EnableDelay bool `protobuf:"varint,10,opt,name=enable_delay,json=enableDelay,proto3" json:"enable_delay,omitempty"`
	// Generator for value series for the target.
	//
	// Types that are valid to be assigned to Generator:
	//	*Config_Custom
	//	*Config_Random
	//	*Config_Fixed
	Generator            isConfig_Generator `protobuf_oneof:"generator"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c8aeeab0e585ec7, []int{2}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *Config) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

// Deprecated: Do not use.
func (m *Config) GetSeed() int64 {
	if m != nil {
		return m.Seed
	}
	return 0
}

// Deprecated: Do not use.
func (m *Config) GetValues() []*Value {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *Config) GetDisableSync() bool {
	if m != nil {
		return m.DisableSync
	}
	return false
}

func (m *Config) GetClientType() Config_ClientType {
	if m != nil {
		return m.ClientType
	}
	return Config_GRPC
}

func (m *Config) GetDisableEof() bool {
	if m != nil {
		return m.DisableEof
	}
	return false
}

func (m *Config) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

func (m *Config) GetCert() []byte {
	if m != nil {
		return m.Cert
	}
	return nil
}

func (m *Config) GetEnableDelay() bool {
	if m != nil {
		return m.EnableDelay
	}
	return false
}

type isConfig_Generator interface {
	isConfig_Generator()
}

type Config_Custom struct {
	Custom *any.Any `protobuf:"bytes,100,opt,name=custom,proto3,oneof"`
}

type Config_Random struct {
	Random *RandomGenerator `protobuf:"bytes,101,opt,name=random,proto3,oneof"`
}

type Config_Fixed struct {
	Fixed *FixedGenerator `protobuf:"bytes,102,opt,name=fixed,proto3,oneof"`
}

func (*Config_Custom) isConfig_Generator() {}

func (*Config_Random) isConfig_Generator() {}

func (*Config_Fixed) isConfig_Generator() {}

func (m *Config) GetGenerator() isConfig_Generator {
	if m != nil {
		return m.Generator
	}
	return nil
}

func (m *Config) GetCustom() *any.Any {
	if x, ok := m.GetGenerator().(*Config_Custom); ok {
		return x.Custom
	}
	return nil
}

func (m *Config) GetRandom() *RandomGenerator {
	if x, ok := m.GetGenerator().(*Config_Random); ok {
		return x.Random
	}
	return nil
}

func (m *Config) GetFixed() *FixedGenerator {
	if x, ok := m.GetGenerator().(*Config_Fixed); ok {
		return x.Fixed
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Config) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Config_Custom)(nil),
		(*Config_Random)(nil),
		(*Config_Fixed)(nil),
	}
}

type FixedGenerator struct {
	Responses            []*gnmi.SubscribeResponse `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *FixedGenerator) Reset()         { *m = FixedGenerator{} }
func (m *FixedGenerator) String() string { return proto.CompactTextString(m) }
func (*FixedGenerator) ProtoMessage()    {}
func (*FixedGenerator) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c8aeeab0e585ec7, []int{3}
}

func (m *FixedGenerator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FixedGenerator.Unmarshal(m, b)
}
func (m *FixedGenerator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FixedGenerator.Marshal(b, m, deterministic)
}
func (m *FixedGenerator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FixedGenerator.Merge(m, src)
}
func (m *FixedGenerator) XXX_Size() int {
	return xxx_messageInfo_FixedGenerator.Size(m)
}
func (m *FixedGenerator) XXX_DiscardUnknown() {
	xxx_messageInfo_FixedGenerator.DiscardUnknown(m)
}

var xxx_messageInfo_FixedGenerator proto.InternalMessageInfo

func (m *FixedGenerator) GetResponses() []*gnmi.SubscribeResponse {
	if m != nil {
		return m.Responses
	}
	return nil
}

type RandomGenerator struct {
	Seed                 int64    `protobuf:"varint,1,opt,name=seed,proto3" json:"seed,omitempty"`
	Values               []*Value `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RandomGenerator) Reset()         { *m = RandomGenerator{} }
func (m *RandomGenerator) String() string { return proto.CompactTextString(m) }
func (*RandomGenerator) ProtoMessage()    {}
func (*RandomGenerator) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c8aeeab0e585ec7, []int{4}
}

func (m *RandomGenerator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RandomGenerator.Unmarshal(m, b)
}
func (m *RandomGenerator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RandomGenerator.Marshal(b, m, deterministic)
}
func (m *RandomGenerator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RandomGenerator.Merge(m, src)
}
func (m *RandomGenerator) XXX_Size() int {
	return xxx_messageInfo_RandomGenerator.Size(m)
}
func (m *RandomGenerator) XXX_DiscardUnknown() {
	xxx_messageInfo_RandomGenerator.DiscardUnknown(m)
}

var xxx_messageInfo_RandomGenerator proto.InternalMessageInfo

func (m *RandomGenerator) GetSeed() int64 {
	if m != nil {
		return m.Seed
	}
	return 0
}

func (m *RandomGenerator) GetValues() []*Value {
	if m != nil {
		return m.Values
	}
	return nil
}

// Delete will cause the value to be deleted at the Value's path.
type DeleteValue struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteValue) Reset()         { *m = DeleteValue{} }
func (m *DeleteValue) String() string { return proto.CompactTextString(m) }
func (*DeleteValue) ProtoMessage()    {}
func (*DeleteValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c8aeeab0e585ec7, []int{5}
}

func (m *DeleteValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteValue.Unmarshal(m, b)
}
func (m *DeleteValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteValue.Marshal(b, m, deterministic)
}
func (m *DeleteValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteValue.Merge(m, src)
}
func (m *DeleteValue) XXX_Size() int {
	return xxx_messageInfo_DeleteValue.Size(m)
}
func (m *DeleteValue) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteValue.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteValue proto.InternalMessageInfo

// Value is the main message that will trigger a stream of updates for a given
// path.  A file containing a list of values can be used to simulate a network
// device for integration tests.
type Value struct {
	// The device specific, or OpenConfig path corresponding to a value.
	Path []string `protobuf:"bytes,1,rep,name=path,proto3" json:"path,omitempty"`
	// The initial timestamp and configuration on how the timestamp will change
	// for subsequent values. If timestamp is not set the default will assume to
	// be the current system time.
	Timestamp *Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// If set, repeat indicates that the value should be repeated this many times,
	// otherwise it is repeated indefinitely.
	Repeat int32 `protobuf:"varint,6,opt,name=repeat,proto3" json:"repeat,omitempty"`
	// A local random seed used in generating subsequent values for this path. If
	// not set, will share the global random source with seed defined in Config.
	Seed int64 `protobuf:"varint,7,opt,name=seed,proto3" json:"seed,omitempty"`
	// The initial value of the chosen type including configuration on how the
	// value will mutate for subsequent updates.
	//
	// Types that are valid to be assigned to Value:
	//	*Value_IntValue
	//	*Value_DoubleValue
	//	*Value_StringValue
	//	*Value_Sync
	//	*Value_Delete
	//	*Value_BoolValue
	Value                isValue_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c8aeeab0e585ec7, []int{6}
}

func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

func (m *Value) GetPath() []string {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *Value) GetTimestamp() *Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Value) GetRepeat() int32 {
	if m != nil {
		return m.Repeat
	}
	return 0
}

func (m *Value) GetSeed() int64 {
	if m != nil {
		return m.Seed
	}
	return 0
}

type isValue_Value interface {
	isValue_Value()
}

type Value_IntValue struct {
	IntValue *IntValue `protobuf:"bytes,100,opt,name=int_value,json=intValue,proto3,oneof"`
}

type Value_DoubleValue struct {
	DoubleValue *DoubleValue `protobuf:"bytes,101,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type Value_StringValue struct {
	StringValue *StringValue `protobuf:"bytes,102,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Value_Sync struct {
	Sync uint64 `protobuf:"varint,103,opt,name=sync,proto3,oneof"`
}

type Value_Delete struct {
	Delete *DeleteValue `protobuf:"bytes,104,opt,name=delete,proto3,oneof"`
}

type Value_BoolValue struct {
	BoolValue *BoolValue `protobuf:"bytes,105,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

func (*Value_IntValue) isValue_Value() {}

func (*Value_DoubleValue) isValue_Value() {}

func (*Value_StringValue) isValue_Value() {}

func (*Value_Sync) isValue_Value() {}

func (*Value_Delete) isValue_Value() {}

func (*Value_BoolValue) isValue_Value() {}

func (m *Value) GetValue() isValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Value) GetIntValue() *IntValue {
	if x, ok := m.GetValue().(*Value_IntValue); ok {
		return x.IntValue
	}
	return nil
}

func (m *Value) GetDoubleValue() *DoubleValue {
	if x, ok := m.GetValue().(*Value_DoubleValue); ok {
		return x.DoubleValue
	}
	return nil
}

func (m *Value) GetStringValue() *StringValue {
	if x, ok := m.GetValue().(*Value_StringValue); ok {
		return x.StringValue
	}
	return nil
}

func (m *Value) GetSync() uint64 {
	if x, ok := m.GetValue().(*Value_Sync); ok {
		return x.Sync
	}
	return 0
}

func (m *Value) GetDelete() *DeleteValue {
	if x, ok := m.GetValue().(*Value_Delete); ok {
		return x.Delete
	}
	return nil
}

func (m *Value) GetBoolValue() *BoolValue {
	if x, ok := m.GetValue().(*Value_BoolValue); ok {
		return x.BoolValue
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Value) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Value_IntValue)(nil),
		(*Value_DoubleValue)(nil),
		(*Value_StringValue)(nil),
		(*Value_Sync)(nil),
		(*Value_Delete)(nil),
		(*Value_BoolValue)(nil),
	}
}

type Timestamp struct {
	// Initial timestamp for the corresponding value, nanoseconds since epoch.
	// This value need have no relation to absolute real-time as the stream of
	// of updates is generated without regard to the real clock and can be run
	// repeatably at any time if the seed is set in the corresponding Value.
	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// These values will vary the change in the timestamp for subsequent outputs
	// by a value between delta_min and delta_max.  Set to the same value to force
	// a set periodic interval.
	DeltaMin             int64    `protobuf:"varint,2,opt,name=delta_min,json=deltaMin,proto3" json:"delta_min,omitempty"`
	DeltaMax             int64    `protobuf:"varint,3,opt,name=delta_max,json=deltaMax,proto3" json:"delta_max,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Timestamp) Reset()         { *m = Timestamp{} }
func (m *Timestamp) String() string { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()    {}
func (*Timestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c8aeeab0e585ec7, []int{7}
}

func (m *Timestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timestamp.Unmarshal(m, b)
}
func (m *Timestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timestamp.Marshal(b, m, deterministic)
}
func (m *Timestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timestamp.Merge(m, src)
}
func (m *Timestamp) XXX_Size() int {
	return xxx_messageInfo_Timestamp.Size(m)
}
func (m *Timestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_Timestamp.DiscardUnknown(m)
}

var xxx_messageInfo_Timestamp proto.InternalMessageInfo

func (m *Timestamp) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Timestamp) GetDeltaMin() int64 {
	if m != nil {
		return m.DeltaMin
	}
	return 0
}

func (m *Timestamp) GetDeltaMax() int64 {
	if m != nil {
		return m.DeltaMax
	}
	return 0
}

type IntValue struct {
	// If distribution is IntRange, value is used as the initial value
	// inside [minimum, maximum] and hold the value as it mutates.
	// If distribution is IntList, value is only used to hold the value as it
	// mutates.
	// If no distribution is set, value is used as it mutates, i.e. constant
	// update.
	Value int64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	// Types that are valid to be assigned to Distribution:
	//	*IntValue_Range
	//	*IntValue_List
	Distribution         isIntValue_Distribution `protobuf_oneof:"distribution"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *IntValue) Reset()         { *m = IntValue{} }
func (m *IntValue) String() string { return proto.CompactTextString(m) }
func (*IntValue) ProtoMessage()    {}
func (*IntValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c8aeeab0e585ec7, []int{8}
}

func (m *IntValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntValue.Unmarshal(m, b)
}
func (m *IntValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntValue.Marshal(b, m, deterministic)
}
func (m *IntValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntValue.Merge(m, src)
}
func (m *IntValue) XXX_Size() int {
	return xxx_messageInfo_IntValue.Size(m)
}
func (m *IntValue) XXX_DiscardUnknown() {
	xxx_messageInfo_IntValue.DiscardUnknown(m)
}

var xxx_messageInfo_IntValue proto.InternalMessageInfo

func (m *IntValue) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type isIntValue_Distribution interface {
	isIntValue_Distribution()
}

type IntValue_Range struct {
	Range *IntRange `protobuf:"bytes,2,opt,name=range,proto3,oneof"`
}

type IntValue_List struct {
	List *IntList `protobuf:"bytes,3,opt,name=list,proto3,oneof"`
}

func (*IntValue_Range) isIntValue_Distribution() {}

func (*IntValue_List) isIntValue_Distribution() {}

func (m *IntValue) GetDistribution() isIntValue_Distribution {
	if m != nil {
		return m.Distribution
	}
	return nil
}

func (m *IntValue) GetRange() *IntRange {
	if x, ok := m.GetDistribution().(*IntValue_Range); ok {
		return x.Range
	}
	return nil
}

func (m *IntValue) GetList() *IntList {
	if x, ok := m.GetDistribution().(*IntValue_List); ok {
		return x.List
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*IntValue) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*IntValue_Range)(nil),
		(*IntValue_List)(nil),
	}
}

type IntRange struct {
	// The range of the value allowed.
	Minimum int64 `protobuf:"varint,1,opt,name=minimum,proto3" json:"minimum,omitempty"`
	Maximum int64 `protobuf:"varint,2,opt,name=maximum,proto3" json:"maximum,omitempty"`
	// If set, the value is cumulative and the subsequent value is value + delta
	// where delta is randomly chosen between delta_min and delta_max.  The range
	// minimum and maximum are still respected and values will saturate at the
	// boundaries if they are exceeded. If not set subsequent value is a value
	// randomly chosen between minimum and maximum.
	DeltaMin             int64    `protobuf:"varint,3,opt,name=delta_min,json=deltaMin,proto3" json:"delta_min,omitempty"`
	DeltaMax             int64    `protobuf:"varint,4,opt,name=delta_max,json=deltaMax,proto3" json:"delta_max,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IntRange) Reset()         { *m = IntRange{} }
func (m *IntRange) String() string { return proto.CompactTextString(m) }
func (*IntRange) ProtoMessage()    {}
func (*IntRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c8aeeab0e585ec7, []int{9}
}

func (m *IntRange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntRange.Unmarshal(m, b)
}
func (m *IntRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntRange.Marshal(b, m, deterministic)
}
func (m *IntRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntRange.Merge(m, src)
}
func (m *IntRange) XXX_Size() int {
	return xxx_messageInfo_IntRange.Size(m)
}
func (m *IntRange) XXX_DiscardUnknown() {
	xxx_messageInfo_IntRange.DiscardUnknown(m)
}

var xxx_messageInfo_IntRange proto.InternalMessageInfo

func (m *IntRange) GetMinimum() int64 {
	if m != nil {
		return m.Minimum
	}
	return 0
}

func (m *IntRange) GetMaximum() int64 {
	if m != nil {
		return m.Maximum
	}
	return 0
}

func (m *IntRange) GetDeltaMin() int64 {
	if m != nil {
		return m.DeltaMin
	}
	return 0
}

func (m *IntRange) GetDeltaMax() int64 {
	if m != nil {
		return m.DeltaMax
	}
	return 0
}

type IntList struct {
	// The set of values which can be used.
	Options []int64 `protobuf:"varint,1,rep,packed,name=options,proto3" json:"options,omitempty"`
	// Set to true to randomize selection of value from options. If false, the
	// values are cycled in order, starting at index 0.
	Random               bool     `protobuf:"varint,2,opt,name=random,proto3" json:"random,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IntList) Reset()         { *m = IntList{} }
func (m *IntList) String() string { return proto.CompactTextString(m) }
func (*IntList) ProtoMessage()    {}
func (*IntList) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c8aeeab0e585ec7, []int{10}
}

func (m *IntList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntList.Unmarshal(m, b)
}
func (m *IntList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntList.Marshal(b, m, deterministic)
}
func (m *IntList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntList.Merge(m, src)
}
func (m *IntList) XXX_Size() int {
	return xxx_messageInfo_IntList.Size(m)
}
func (m *IntList) XXX_DiscardUnknown() {
	xxx_messageInfo_IntList.DiscardUnknown(m)
}

var xxx_messageInfo_IntList proto.InternalMessageInfo

func (m *IntList) GetOptions() []int64 {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *IntList) GetRandom() bool {
	if m != nil {
		return m.Random
	}
	return false
}

type DoubleValue struct {
	// If distribution is DoubleRange, value is used as the initial value
	// inside [minimum, maximum] and hold the value as it mutates.
	// If distribution is DoubleList, value is only used to hold the value as it
	// mutates.
	// If no distribution is set, value is used as it mutates, i.e. constant
	// update.
	Value float64 `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	// Types that are valid to be assigned to Distribution:
	//	*DoubleValue_Range
	//	*DoubleValue_List
	Distribution         isDoubleValue_Distribution `protobuf_oneof:"distribution"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *DoubleValue) Reset()         { *m = DoubleValue{} }
func (m *DoubleValue) String() string { return proto.CompactTextString(m) }
func (*DoubleValue) ProtoMessage()    {}
func (*DoubleValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c8aeeab0e585ec7, []int{11}
}

func (m *DoubleValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoubleValue.Unmarshal(m, b)
}
func (m *DoubleValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoubleValue.Marshal(b, m, deterministic)
}
func (m *DoubleValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoubleValue.Merge(m, src)
}
func (m *DoubleValue) XXX_Size() int {
	return xxx_messageInfo_DoubleValue.Size(m)
}
func (m *DoubleValue) XXX_DiscardUnknown() {
	xxx_messageInfo_DoubleValue.DiscardUnknown(m)
}

var xxx_messageInfo_DoubleValue proto.InternalMessageInfo

func (m *DoubleValue) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type isDoubleValue_Distribution interface {
	isDoubleValue_Distribution()
}

type DoubleValue_Range struct {
	Range *DoubleRange `protobuf:"bytes,2,opt,name=range,proto3,oneof"`
}

type DoubleValue_List struct {
	List *DoubleList `protobuf:"bytes,3,opt,name=list,proto3,oneof"`
}

func (*DoubleValue_Range) isDoubleValue_Distribution() {}

func (*DoubleValue_List) isDoubleValue_Distribution() {}

func (m *DoubleValue) GetDistribution() isDoubleValue_Distribution {
	if m != nil {
		return m.Distribution
	}
	return nil
}

func (m *DoubleValue) GetRange() *DoubleRange {
	if x, ok := m.GetDistribution().(*DoubleValue_Range); ok {
		return x.Range
	}
	return nil
}

func (m *DoubleValue) GetList() *DoubleList {
	if x, ok := m.GetDistribution().(*DoubleValue_List); ok {
		return x.List
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*DoubleValue) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DoubleValue_Range)(nil),
		(*DoubleValue_List)(nil),
	}
}

type DoubleRange struct {
	// The range of the value allowed.
	Minimum float64 `protobuf:"fixed64,1,opt,name=minimum,proto3" json:"minimum,omitempty"`
	Maximum float64 `protobuf:"fixed64,2,opt,name=maximum,proto3" json:"maximum,omitempty"`
	// If set, the value is cumulative and the subsequent value is value + delta
	// where delta is randomly chosen between delta_min and delta_max. The range
	// minimum and maximum are still respected. If not set subsequent value is a
	// value randomly chosen between minimum and maximum.
	DeltaMin             float64  `protobuf:"fixed64,3,opt,name=delta_min,json=deltaMin,proto3" json:"delta_min,omitempty"`
	DeltaMax             float64  `protobuf:"fixed64,4,opt,name=delta_max,json=deltaMax,proto3" json:"delta_max,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DoubleRange) Reset()         { *m = DoubleRange{} }
func (m *DoubleRange) String() string { return proto.CompactTextString(m) }
func (*DoubleRange) ProtoMessage()    {}
func (*DoubleRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c8aeeab0e585ec7, []int{12}
}

func (m *DoubleRange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoubleRange.Unmarshal(m, b)
}
func (m *DoubleRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoubleRange.Marshal(b, m, deterministic)
}
func (m *DoubleRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoubleRange.Merge(m, src)
}
func (m *DoubleRange) XXX_Size() int {
	return xxx_messageInfo_DoubleRange.Size(m)
}
func (m *DoubleRange) XXX_DiscardUnknown() {
	xxx_messageInfo_DoubleRange.DiscardUnknown(m)
}

var xxx_messageInfo_DoubleRange proto.InternalMessageInfo

func (m *DoubleRange) GetMinimum() float64 {
	if m != nil {
		return m.Minimum
	}
	return 0
}

func (m *DoubleRange) GetMaximum() float64 {
	if m != nil {
		return m.Maximum
	}
	return 0
}

func (m *DoubleRange) GetDeltaMin() float64 {
	if m != nil {
		return m.DeltaMin
	}
	return 0
}

func (m *DoubleRange) GetDeltaMax() float64 {
	if m != nil {
		return m.DeltaMax
	}
	return 0
}

type DoubleList struct {
	// The set of values which can be used.
	Options []float64 `protobuf:"fixed64,1,rep,packed,name=options,proto3" json:"options,omitempty"`
	// Set to true to randomize selection of value from options. If false, the
	// values are cycled in order.
	Random               bool     `protobuf:"varint,2,opt,name=random,proto3" json:"random,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DoubleList) Reset()         { *m = DoubleList{} }
func (m *DoubleList) String() string { return proto.CompactTextString(m) }
func (*DoubleList) ProtoMessage()    {}
func (*DoubleList) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c8aeeab0e585ec7, []int{13}
}

func (m *DoubleList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoubleList.Unmarshal(m, b)
}
func (m *DoubleList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoubleList.Marshal(b, m, deterministic)
}
func (m *DoubleList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoubleList.Merge(m, src)
}
func (m *DoubleList) XXX_Size() int {
	return xxx_messageInfo_DoubleList.Size(m)
}
func (m *DoubleList) XXX_DiscardUnknown() {
	xxx_messageInfo_DoubleList.DiscardUnknown(m)
}

var xxx_messageInfo_DoubleList proto.InternalMessageInfo

func (m *DoubleList) GetOptions() []float64 {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *DoubleList) GetRandom() bool {
	if m != nil {
		return m.Random
	}
	return false
}

type StringValue struct {
	// If distribution is StringList, value is used to hold the value as it
	// mutates.
	// If no distribution is set, value is used as it mutates, i.e. constant
	// update.
	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	// Types that are valid to be assigned to Distribution:
	//	*StringValue_List
	Distribution         isStringValue_Distribution `protobuf_oneof:"distribution"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *StringValue) Reset()         { *m = StringValue{} }
func (m *StringValue) String() string { return proto.CompactTextString(m) }
func (*StringValue) ProtoMessage()    {}
func (*StringValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c8aeeab0e585ec7, []int{14}
}

func (m *StringValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringValue.Unmarshal(m, b)
}
func (m *StringValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringValue.Marshal(b, m, deterministic)
}
func (m *StringValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringValue.Merge(m, src)
}
func (m *StringValue) XXX_Size() int {
	return xxx_messageInfo_StringValue.Size(m)
}
func (m *StringValue) XXX_DiscardUnknown() {
	xxx_messageInfo_StringValue.DiscardUnknown(m)
}

var xxx_messageInfo_StringValue proto.InternalMessageInfo

func (m *StringValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type isStringValue_Distribution interface {
	isStringValue_Distribution()
}

type StringValue_List struct {
	List *StringList `protobuf:"bytes,2,opt,name=list,proto3,oneof"`
}

func (*StringValue_List) isStringValue_Distribution() {}

func (m *StringValue) GetDistribution() isStringValue_Distribution {
	if m != nil {
		return m.Distribution
	}
	return nil
}

func (m *StringValue) GetList() *StringList {
	if x, ok := m.GetDistribution().(*StringValue_List); ok {
		return x.List
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StringValue) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StringValue_List)(nil),
	}
}

type StringList struct {
	// The set of strings which can be used.
	Options []string `protobuf:"bytes,1,rep,name=options,proto3" json:"options,omitempty"`
	// Set to true to randomize selection of value from options. If false, the
	// values are cycled in order, starting at index 0.
	Random               bool     `protobuf:"varint,2,opt,name=random,proto3" json:"random,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringList) Reset()         { *m = StringList{} }
func (m *StringList) String() string { return proto.CompactTextString(m) }
func (*StringList) ProtoMessage()    {}
func (*StringList) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c8aeeab0e585ec7, []int{15}
}

func (m *StringList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringList.Unmarshal(m, b)
}
func (m *StringList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringList.Marshal(b, m, deterministic)
}
func (m *StringList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringList.Merge(m, src)
}
func (m *StringList) XXX_Size() int {
	return xxx_messageInfo_StringList.Size(m)
}
func (m *StringList) XXX_DiscardUnknown() {
	xxx_messageInfo_StringList.DiscardUnknown(m)
}

var xxx_messageInfo_StringList proto.InternalMessageInfo

func (m *StringList) GetOptions() []string {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *StringList) GetRandom() bool {
	if m != nil {
		return m.Random
	}
	return false
}

type BoolValue struct {
	// If distribution is BoolList, value is only used to hold the value as it
	// mutates.
	// If no distribution is set, value is used as it mutates, i.e. constant
	// update.
	Value bool `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	// Types that are valid to be assigned to Distribution:
	//	*BoolValue_List
	Distribution         isBoolValue_Distribution `protobuf_oneof:"distribution"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *BoolValue) Reset()         { *m = BoolValue{} }
func (m *BoolValue) String() string { return proto.CompactTextString(m) }
func (*BoolValue) ProtoMessage()    {}
func (*BoolValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c8aeeab0e585ec7, []int{16}
}

func (m *BoolValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoolValue.Unmarshal(m, b)
}
func (m *BoolValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoolValue.Marshal(b, m, deterministic)
}
func (m *BoolValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoolValue.Merge(m, src)
}
func (m *BoolValue) XXX_Size() int {
	return xxx_messageInfo_BoolValue.Size(m)
}
func (m *BoolValue) XXX_DiscardUnknown() {
	xxx_messageInfo_BoolValue.DiscardUnknown(m)
}

var xxx_messageInfo_BoolValue proto.InternalMessageInfo

func (m *BoolValue) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

type isBoolValue_Distribution interface {
	isBoolValue_Distribution()
}

type BoolValue_List struct {
	List *BoolList `protobuf:"bytes,2,opt,name=list,proto3,oneof"`
}

func (*BoolValue_List) isBoolValue_Distribution() {}

func (m *BoolValue) GetDistribution() isBoolValue_Distribution {
	if m != nil {
		return m.Distribution
	}
	return nil
}

func (m *BoolValue) GetList() *BoolList {
	if x, ok := m.GetDistribution().(*BoolValue_List); ok {
		return x.List
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*BoolValue) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*BoolValue_List)(nil),
	}
}

type BoolList struct {
	// The set of values which can be used.
	Options []bool `protobuf:"varint,1,rep,packed,name=options,proto3" json:"options,omitempty"`
	// Set to true to randomize selection of value from options. If false, the
	// values are cycled in order, starting at index 0.
	Random               bool     `protobuf:"varint,2,opt,name=random,proto3" json:"random,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoolList) Reset()         { *m = BoolList{} }
func (m *BoolList) String() string { return proto.CompactTextString(m) }
func (*BoolList) ProtoMessage()    {}
func (*BoolList) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c8aeeab0e585ec7, []int{17}
}

func (m *BoolList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoolList.Unmarshal(m, b)
}
func (m *BoolList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoolList.Marshal(b, m, deterministic)
}
func (m *BoolList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoolList.Merge(m, src)
}
func (m *BoolList) XXX_Size() int {
	return xxx_messageInfo_BoolList.Size(m)
}
func (m *BoolList) XXX_DiscardUnknown() {
	xxx_messageInfo_BoolList.DiscardUnknown(m)
}

var xxx_messageInfo_BoolList proto.InternalMessageInfo

func (m *BoolList) GetOptions() []bool {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *BoolList) GetRandom() bool {
	if m != nil {
		return m.Random
	}
	return false
}

func init() {
	proto.RegisterEnum("gnmi.fake.State", State_name, State_value)
	proto.RegisterEnum("gnmi.fake.Config_ClientType", Config_ClientType_name, Config_ClientType_value)
	proto.RegisterType((*Configuration)(nil), "gnmi.fake.Configuration")
	proto.RegisterType((*Credentials)(nil), "gnmi.fake.Credentials")
	proto.RegisterType((*Config)(nil), "gnmi.fake.Config")
	proto.RegisterType((*FixedGenerator)(nil), "gnmi.fake.FixedGenerator")
	proto.RegisterType((*RandomGenerator)(nil), "gnmi.fake.RandomGenerator")
	proto.RegisterType((*DeleteValue)(nil), "gnmi.fake.DeleteValue")
	proto.RegisterType((*Value)(nil), "gnmi.fake.Value")
	proto.RegisterType((*Timestamp)(nil), "gnmi.fake.Timestamp")
	proto.RegisterType((*IntValue)(nil), "gnmi.fake.IntValue")
	proto.RegisterType((*IntRange)(nil), "gnmi.fake.IntRange")
	proto.RegisterType((*IntList)(nil), "gnmi.fake.IntList")
	proto.RegisterType((*DoubleValue)(nil), "gnmi.fake.DoubleValue")
	proto.RegisterType((*DoubleRange)(nil), "gnmi.fake.DoubleRange")
	proto.RegisterType((*DoubleList)(nil), "gnmi.fake.DoubleList")
	proto.RegisterType((*StringValue)(nil), "gnmi.fake.StringValue")
	proto.RegisterType((*StringList)(nil), "gnmi.fake.StringList")
	proto.RegisterType((*BoolValue)(nil), "gnmi.fake.BoolValue")
	proto.RegisterType((*BoolList)(nil), "gnmi.fake.BoolList")
}

func init() { proto.RegisterFile("testing/fake/proto/fake.proto", fileDescriptor_0c8aeeab0e585ec7) }

var fileDescriptor_0c8aeeab0e585ec7 = []byte{
	// 1114 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0xdf, 0x6e, 0xe3, 0xc4,
	0x17, 0xae, 0xf3, 0xdf, 0xc7, 0x6d, 0x7f, 0xf9, 0xcd, 0x96, 0xe2, 0x2d, 0x8b, 0x08, 0xbe, 0xca,
	0x52, 0x94, 0x2e, 0x81, 0x95, 0x10, 0x0b, 0x2b, 0x35, 0x6d, 0x69, 0x2b, 0xd1, 0x3f, 0x9a, 0x74,
	0x91, 0x90, 0x90, 0xc2, 0x24, 0x9e, 0xb8, 0x16, 0xf1, 0x4c, 0x64, 0x4f, 0x96, 0x46, 0x3c, 0x00,
	0xb7, 0xdc, 0xf3, 0x14, 0x3c, 0x0f, 0x2f, 0x83, 0xe6, 0x78, 0x1c, 0x3b, 0xc9, 0x92, 0xee, 0xdd,
	0x9c, 0x73, 0xbe, 0x73, 0xe6, 0x9b, 0x6f, 0xbe, 0x89, 0x03, 0x1f, 0x2b, 0x9e, 0xa8, 0x50, 0x04,
	0x47, 0x63, 0xf6, 0x2b, 0x3f, 0x9a, 0xc6, 0x52, 0x49, 0x5c, 0x76, 0x70, 0x49, 0xec, 0x40, 0x44,
	0x61, 0x47, 0x27, 0x0e, 0x9e, 0x06, 0x52, 0x06, 0x13, 0x83, 0x19, 0xce, 0xc6, 0x47, 0x4c, 0xcc,
	0x53, 0xd4, 0xc1, 0x8b, 0x20, 0x54, 0xf7, 0xb3, 0x61, 0x67, 0x24, 0xa3, 0x23, 0x39, 0xe5, 0x62,
	0x24, 0xc5, 0x38, 0x0c, 0x8e, 0x74, 0xaf, 0x19, 0x89, 0x4b, 0x9c, 0x85, 0xb1, 0xf7, 0x0d, 0xec,
	0x9c, 0x20, 0x68, 0x16, 0x33, 0x15, 0x4a, 0x41, 0x9e, 0x43, 0x2d, 0xed, 0x72, 0xad, 0x56, 0xb9,
	0xed, 0x74, 0xff, 0xdf, 0x59, 0xec, 0xdc, 0x49, 0x91, 0xd4, 0x00, 0xbc, 0x33, 0x70, 0x4e, 0x62,
	0xee, 0x73, 0xa1, 0x42, 0x36, 0x49, 0xc8, 0x01, 0x34, 0x66, 0x09, 0x8f, 0x05, 0x8b, 0xb8, 0x6b,
	0xb5, 0xac, 0xb6, 0x4d, 0x17, 0xb1, 0xae, 0x4d, 0x59, 0x92, 0xfc, 0x26, 0x63, 0xdf, 0x2d, 0xa5,
	0xb5, 0x2c, 0xf6, 0xfe, 0xa9, 0x40, 0x2d, 0x9d, 0x4c, 0xf6, 0xa1, 0xa6, 0x58, 0x1c, 0x70, 0x65,
	0x06, 0x98, 0x88, 0x10, 0xa8, 0x4c, 0x65, 0xac, 0xb0, 0xb5, 0x4a, 0x71, 0x4d, 0xf6, 0xa1, 0x92,
	0x70, 0xee, 0xbb, 0xb5, 0x96, 0xd5, 0x2e, 0xf7, 0x4a, 0xae, 0x45, 0x31, 0x26, 0x9f, 0x43, 0xed,
	0x2d, 0x9b, 0xcc, 0x78, 0xe2, 0x96, 0xf1, 0x00, 0xcd, 0xc2, 0x01, 0x7e, 0xd4, 0x05, 0xc4, 0x1a,
	0x0c, 0xf9, 0x14, 0xb6, 0xfd, 0x30, 0x61, 0xc3, 0x09, 0x1f, 0x24, 0x73, 0x31, 0x72, 0x2b, 0x2d,
	0xab, 0xdd, 0xa0, 0x8e, 0xc9, 0xf5, 0xe7, 0x62, 0x44, 0xbe, 0x03, 0x67, 0x34, 0x09, 0xb9, 0x50,
	0x03, 0x35, 0x9f, 0x72, 0xb7, 0xda, 0xb2, 0xda, 0xbb, 0xdd, 0x67, 0x6b, 0xb2, 0x74, 0x4e, 0x10,
	0x74, 0x37, 0x9f, 0x72, 0x0a, 0xa3, 0xc5, 0x9a, 0x7c, 0x02, 0xd9, 0xb4, 0x01, 0x97, 0x63, 0xb7,
	0x8e, 0x1b, 0x80, 0x49, 0x9d, 0xc9, 0x31, 0xf9, 0x1a, 0x9c, 0x51, 0x2e, 0xa3, 0xdb, 0x68, 0x59,
	0x6d, 0xa7, 0xbb, 0x5f, 0x9c, 0x9f, 0x57, 0x69, 0x11, 0xaa, 0x65, 0x19, 0xf1, 0x58, 0xb9, 0x76,
	0xcb, 0x6a, 0x6f, 0x53, 0x5c, 0xeb, 0x03, 0x71, 0x81, 0xbb, 0xf9, 0x7c, 0xc2, 0xe6, 0x2e, 0xa4,
	0x07, 0x4a, 0x73, 0xa7, 0x3a, 0x45, 0x3a, 0x50, 0x1b, 0xcd, 0x12, 0x25, 0x23, 0xd7, 0xc7, 0xbd,
	0xf6, 0x3a, 0xa9, 0xa3, 0x3a, 0x99, 0xa3, 0x3a, 0xc7, 0x62, 0x7e, 0xb1, 0x45, 0x0d, 0x8a, 0x7c,
	0x05, 0xb5, 0x98, 0x09, 0x5f, 0x46, 0x2e, 0x47, 0xfc, 0x41, 0x81, 0x1b, 0xc5, 0xc2, 0x39, 0x17,
	0x3c, 0x66, 0x4a, 0xc6, 0xba, 0x2b, 0xc5, 0x92, 0x2f, 0xa0, 0x3a, 0x0e, 0x1f, 0xb8, 0xef, 0x8e,
	0xb1, 0xe9, 0x69, 0xa1, 0xe9, 0x7b, 0x9d, 0x2f, 0xf6, 0xa4, 0x48, 0xef, 0x0c, 0x20, 0x17, 0x91,
	0x34, 0xa0, 0x72, 0x4e, 0x6f, 0x4f, 0x9a, 0x5b, 0x04, 0xa0, 0xd6, 0xbf, 0x7b, 0xd3, 0xeb, 0xfd,
	0xd4, 0xb4, 0xc8, 0x0e, 0xd8, 0x3a, 0x3b, 0x38, 0xbf, 0xbe, 0xba, 0x6c, 0x96, 0x08, 0x81, 0xdd,
	0x45, 0x38, 0xb8, 0xa5, 0x37, 0xa7, 0xcd, 0x72, 0xcf, 0x01, 0x3b, 0xc8, 0x86, 0x7b, 0xe7, 0xb0,
	0xbb, 0xbc, 0x1d, 0x79, 0x09, 0x76, 0xcc, 0x93, 0xa9, 0x14, 0x09, 0x4f, 0x8c, 0xc9, 0x3f, 0x4c,
	0xc9, 0xf5, 0x67, 0xc3, 0x64, 0x14, 0x87, 0x43, 0x4e, 0x4d, 0x9d, 0xe6, 0x48, 0xef, 0x06, 0xfe,
	0xb7, 0x72, 0x58, 0xad, 0x3f, 0x5a, 0x50, 0x9b, 0xb5, 0x6c, 0xec, 0xd7, 0x5e, 0xd8, 0xaf, 0xf4,
	0x6e, 0xfb, 0x65, 0xd6, 0xf3, 0x76, 0xc0, 0x39, 0xe5, 0x13, 0xae, 0x38, 0xa6, 0xbd, 0xbf, 0xcb,
	0x50, 0xc5, 0x15, 0xba, 0x9d, 0xa9, 0x7b, 0xe4, 0x66, 0x53, 0x5c, 0x93, 0x2e, 0xd8, 0x2a, 0x8c,
	0x78, 0xa2, 0x58, 0x34, 0xc5, 0x67, 0x80, 0xd7, 0xb6, 0x98, 0x7c, 0x97, 0xd5, 0x68, 0x0e, 0xd3,
	0xaf, 0x29, 0xe6, 0x53, 0xce, 0x14, 0xbe, 0x91, 0x2a, 0x35, 0xd1, 0x82, 0x76, 0xbd, 0x40, 0xbb,
	0x0b, 0x76, 0x28, 0xd4, 0x00, 0xa9, 0x19, 0x5b, 0x3c, 0x29, 0xcc, 0xbf, 0x14, 0x0a, 0xb9, 0x5d,
	0x6c, 0xd1, 0x46, 0x68, 0xd6, 0xe4, 0x15, 0x6c, 0xfb, 0x72, 0xa6, 0xad, 0x96, 0xb6, 0xf1, 0x35,
	0xe7, 0x9e, 0x62, 0x39, 0xeb, 0x74, 0xfc, 0x3c, 0xd4, 0xcd, 0x89, 0x8a, 0x43, 0x11, 0x98, 0xe6,
	0xf1, 0x5a, 0x73, 0x1f, 0xcb, 0x8b, 0xe6, 0x24, 0x0f, 0xc9, 0x1e, 0x54, 0xf0, 0xb5, 0x06, 0x2d,
	0xab, 0x5d, 0xb9, 0xd8, 0xa2, 0x18, 0x91, 0x17, 0x50, 0xf3, 0x51, 0x50, 0xf7, 0x7e, 0x9d, 0x49,
	0xae, 0xb4, 0xf6, 0x68, 0x8a, 0x23, 0x2f, 0x01, 0x86, 0x52, 0x4e, 0x0c, 0x85, 0x70, 0x4d, 0xd6,
	0x9e, 0x94, 0x93, 0xac, 0xc7, 0x1e, 0x66, 0x41, 0xaf, 0x0e, 0x55, 0xec, 0xf0, 0x46, 0x60, 0x2f,
	0x94, 0x27, 0xcf, 0x8a, 0x57, 0x94, 0x5a, 0xa2, 0x70, 0x19, 0x1f, 0x81, 0xed, 0xf3, 0x89, 0x62,
	0x83, 0x28, 0x14, 0x78, 0x81, 0x65, 0xda, 0xc0, 0xc4, 0x55, 0x28, 0x0a, 0x45, 0xf6, 0xe0, 0x96,
	0x8b, 0x45, 0xf6, 0xe0, 0xfd, 0x61, 0x41, 0x23, 0xd3, 0x9f, 0xec, 0x99, 0xad, 0xcd, 0x06, 0x69,
	0x40, 0x0e, 0xa1, 0x1a, 0x33, 0x11, 0x70, 0xe3, 0x8c, 0x95, 0x9b, 0xa3, 0xba, 0xa4, 0x5f, 0x19,
	0x62, 0x48, 0x1b, 0x2a, 0x93, 0x30, 0x51, 0xb8, 0x8f, 0xd3, 0x25, 0xcb, 0xd8, 0x1f, 0xc2, 0x44,
	0x69, 0x41, 0x35, 0xa2, 0xb7, 0x8b, 0x3f, 0x8e, 0x2a, 0x0e, 0x87, 0x33, 0xfd, 0x6d, 0xf0, 0x1e,
	0x90, 0x08, 0x8e, 0x23, 0x2e, 0xd4, 0xa3, 0x50, 0x84, 0xd1, 0x2c, 0x32, 0x54, 0xb2, 0x10, 0x2b,
	0xec, 0x01, 0x2b, 0x25, 0x53, 0x49, 0xc3, 0x65, 0x0d, 0xca, 0x9b, 0x34, 0xa8, 0xac, 0x68, 0xf0,
	0x0a, 0xea, 0x86, 0x9c, 0x1e, 0x2f, 0xa7, 0x9a, 0x4e, 0xfa, 0x78, 0xcb, 0x34, 0x0b, 0xd1, 0xef,
	0xe9, 0xef, 0x54, 0x09, 0x7f, 0xf4, 0x4c, 0xe4, 0xfd, 0x69, 0x81, 0x53, 0x70, 0xe2, 0xb2, 0x86,
	0x56, 0xa6, 0x61, 0x67, 0x59, 0xc3, 0x75, 0x1b, 0xaf, 0xc8, 0x78, 0xb8, 0x24, 0xe3, 0x07, 0x6b,
	0xf0, 0x8d, 0x4a, 0xfe, 0x9e, 0x31, 0x7a, 0xa7, 0x98, 0xd6, 0x7f, 0x8a, 0x69, 0x6d, 0x10, 0xd3,
	0xda, 0x24, 0xa6, 0x55, 0x10, 0xf3, 0x35, 0x40, 0x4e, 0x71, 0x55, 0x4f, 0xeb, 0x71, 0x3d, 0x7f,
	0x01, 0xa7, 0xbf, 0xf4, 0x18, 0x0b, 0x72, 0xda, 0xb9, 0x25, 0x53, 0x79, 0x4a, 0x6b, 0xf2, 0xa4,
	0xbd, 0x1b, 0xe5, 0x79, 0x0d, 0x90, 0xa3, 0x56, 0x19, 0xda, 0x8f, 0x33, 0xfc, 0x19, 0xec, 0xc5,
	0xd3, 0x5d, 0xe6, 0xd7, 0xc8, 0xf8, 0x3d, 0x5f, 0xe2, 0xf7, 0x64, 0xe5, 0xd1, 0x6f, 0x64, 0xf7,
	0x2d, 0x34, 0x32, 0xcc, 0x2a, 0xb7, 0xc6, 0xa3, 0xdc, 0x3e, 0x3b, 0x84, 0x6a, 0x5f, 0x31, 0xc5,
	0x89, 0x03, 0xf5, 0xfe, 0xdd, 0xcd, 0xed, 0xed, 0xd9, 0x69, 0x73, 0x4b, 0x7f, 0xec, 0x2e, 0xaf,
	0x2f, 0xef, 0x9a, 0x96, 0x4e, 0xd3, 0x37, 0xd7, 0xd7, 0x97, 0xd7, 0xe7, 0xcd, 0x52, 0xf7, 0x2f,
	0x0b, 0xb6, 0x8f, 0x03, 0x2e, 0xd4, 0x15, 0x13, 0x2c, 0xe0, 0x31, 0x39, 0x84, 0xf2, 0xb1, 0xef,
	0x93, 0xf5, 0x7f, 0x65, 0x07, 0xeb, 0x29, 0xfd, 0xa1, 0xa7, 0x3c, 0x92, 0x6f, 0xf9, 0xfb, 0xe3,
	0x35, 0xb5, 0x59, 0xf2, 0x7e, 0xf8, 0x61, 0x0d, 0xff, 0x30, 0x7c, 0xf9, 0x6f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xaf, 0x6d, 0xfc, 0x30, 0xbc, 0x0a, 0x00, 0x00,
}
